#!/usr/bin/python3

import re
import sys

pointers = {
    'prethink'  : 'void {p}(edict_t *)',
    'think'     : 'void {p}(edict_t *)',
    'blocked'   : 'void {p}(edict_t *, edict_t *)',
    'touch'     : 'void {p}(edict_t *, edict_t *, cplane_t *, csurface_t *)',
    'use'       : 'void {p}(edict_t *, edict_t *, edict_t *)',
    'pain'      : 'void {p}(edict_t *, edict_t *, float, int)',
    'die'       : 'void {p}(edict_t *, edict_t *, edict_t *, int, vec3_t)',
    'moveinfo_endfunc'          : 'void {p}(edict_t *)',
    'monsterinfo_currentmove'   : 'const mmove_t {p}',
    'monsterinfo_stand'         : 'void {p}(edict_t *)',
    'monsterinfo_idle'          : 'void {p}(edict_t *)',
    'monsterinfo_search'        : 'void {p}(edict_t *)',
    'monsterinfo_walk'          : 'void {p}(edict_t *)',
    'monsterinfo_run'           : 'void {p}(edict_t *)',
    'monsterinfo_dodge'         : 'void {p}(edict_t *, edict_t *, float, trace_t *)',
    'monsterinfo_attack'        : 'void {p}(edict_t *)',
    'monsterinfo_melee'         : 'void {p}(edict_t *)',
    'monsterinfo_sight'         : 'void {p}(edict_t *, edict_t *)',
    'monsterinfo_checkattack'   : 'bool {p}(edict_t *)',
    # ROGUE
    'monsterinfo_blocked'       : 'bool {p}(edict_t *, float)',
    'monsterinfo_duck'          : 'void {p}(edict_t *, float)',
    'monsterinfo_unduck'        : 'void {p}(edict_t *)',
    'monsterinfo_sidestep'      : 'void {p}(edict_t *)',
    # ROGUE
}

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print('Usage: genptr.py <file> [...]')
        sys.exit(1)

    exprs = '|'.join(p.replace('_', '\\.') for p in pointers.keys() if not p == 'moveinfo_endfunc')
    regex = re.compile(r'->\s*(%s)\s*=\s*&?\s*(\w+)' % exprs, re.ASCII)
    regex2 = re.compile(r'\b(?:Angle)?Move_Calc\s*\(.+,\s*(\w+)\s*\)', re.ASCII)

    types = {}
    for p in pointers.keys():
        types[p] = []

    # Collect the macros the sources actually define, so blocks guarded by
    # feature switches that are never set (INCLUDE_INCENDIARY, ...) are skipped;
    # otherwise we would emit externs for functions that do not exist.
    defined = set()
    for a in sys.argv[1:]:
        with open(a) as f:
            for line in f:
                m = re.match(r'\s*#\s*define\s+(\w+)', line)
                if m:
                    defined.add(m.group(1))

    for a in sys.argv[1:]:
        skip = 0          # nesting depth inside an inactive #if block
        depth = 0
        incomment = False
        with open(a) as f:
            for line in f:
                # block comments hide code just as effectively as #if 0
                if incomment:
                    if '*/' in line:
                        incomment = False
                        line = line.split('*/', 1)[1]
                    else:
                        continue
                while '/*' in line:
                    head, rest = line.split('/*', 1)
                    if '*/' in rest:
                        line = head + rest.split('*/', 1)[1]
                    else:
                        line = head
                        incomment = True
                        break
                s = line.strip()
                if s.startswith('#'):
                    m = re.match(r'#\s*(ifdef|ifndef|if|else|elif|endif)\b(.*)', s)
                    if m:
                        kind, rest = m.group(1), m.group(2).strip()
                        if kind in ('ifdef', 'ifndef', 'if'):
                            depth += 1
                            if not skip:
                                inactive = (kind == 'ifdef' and rest not in defined) or \
                                           (kind == 'if' and rest == '0')
                                if inactive:
                                    skip = depth
                        elif kind == 'endif':
                            if skip == depth:
                                skip = 0
                            depth -= 1
                        elif kind in ('else', 'elif') and skip == depth:
                            skip = 0
                    continue
                if skip:
                    continue
                if not line.lstrip().startswith('//'):
                    match = regex.search(line)
                    if match:
                        t = types[match[1].replace('.', '_')]
                        p = match[2]
                        if not p in t and p != 'NULL':
                            t.append(p)
                        continue

                    match = regex2.search(line)
                    if match:
                        t = types['moveinfo_endfunc']
                        p = match[1]
                        if not p in t:
                            t.append(p)


    print('// generated by genptr.py, do not modify')
    print('#include "g_local.h"')
    print('#include "g_ptrs.h"')

    decls = []
    for k, v in types.items():
        for p in v:
            decls.append('extern ' + pointers[k].replace('{p}', p) + ';')
    for d in sorted(decls, key=str.lower):
        print(d)

    print('const save_ptr_t save_ptrs[] = {')
    for k, v in types.items():
        for p in sorted(v, key=str.lower):
            amp = '&' if k == 'monsterinfo_currentmove' else ''
            print('{ %s, %s%s },' % ('P_' + k, amp, p))
    print('};')
    print('const int num_save_ptrs = sizeof(save_ptrs) / sizeof(save_ptrs[0]);')
